### ISSUE TITLE
Is there a guide or tutorial on how to use this?

### ISSUE THREAD

**Issue by vesper8** [VoidXH/Trivia-Murder-Party-Modder#1]
I just discovered Jackbox on New Year's Eve and the Trivia Murder Party was indeed by far the most well received game and most polished. The idea that you could mod the questions, audio and other aspects of it sounds super interesting!

I was wondering if maybe you already published a guide, youtube video or any kind of tutorial on how to use this? I noticed the readme is quite slim and on first look I have no idea what I'm supposed to do so I would appreciate any guidance

Thanks a lot and happy new year's!

**Comment by VoidXH** [comment]
Happy New Year, I've just updated the readme with a user documentation.
