### ISSUE TITLE
Response to last question

### ISSUE THREAD

**Issue by aperturegame** [VoidXH/Trivia-Murder-Party-Modder#11]
Well, I just tested it. It works with TMP2(didn't test it in-game yet, but i can access the files and add questions, so i think it works.). Also, might wanna mention you need to enter the TDQuestion.jet file, since there's another file called TDQuestion where all the questions are stored.
Can't access the quiplash content, unfortunately.

**Comment by VoidXH** [comment]
> Also, might wanna mention you need to enter the TDQuestion.jet file, since there's another file called TDQuestion where all the questions are stored.

So it works, but TMP2 has no extension and has to be manually imported? Does the release check work?

> Can't access the quiplash content, unfortunately.

That is expected, this software is for TMP only.

**Comment by aperturegame** [comment]
I don't know how this works with TMP1, so I have no idea what you mean by 'extension' and 'manually imported'. I press import, select TDQuestion.jet, and then I can add questions.
Getting late for me, so i'll test the release check tomorrow.

**Comment by aperturegame** [comment]
Release check works.
I can't use the 'import all' button(probably because its looking for pack 3 and not pack 6), so i have to import manually. I can add questions and audio.
One last question, what do the audio files sound like in TMP1? The TMP2 files seem to sound more...normal than what you actually hear in game, so I think the game automatically pitches them down.

**Comment by aperturegame** [comment]
Also, obviously, I can access and change the quiplash content with a quiplash question editor.

**Comment by VoidXH** [comment]
Thanks, compatibility info is added to the Readme. I don't know about the sound files, they might have added the distortion into the game instead of the files this time. That's good, in this case you don't have to worry about it while modding.
