### ISSUE TITLE
FinalRound audio problem

### ISSUE THREAD

**Issue by mistagee83** [VoidXH/Trivia-Murder-Party-Modder#12]
Whenever I want to import an audio file into a FinalRound question, I get the prompt "Select something to which you want to import the audio". But the topic is already selected. What am I doing wrong?

**Comment by VoidXH** [comment]
Fixed in d1d0b77be844e602d01a6948628c3af107954ddd, released.

**Comment by mistagee83** [comment]
![bug](https://user-images.githubusercontent.com/128312882/226210835-ad1cbe08-6d80-4977-848d-6242ca2961c3.jpg)
I'm not a programmer, I don't really know what happened, but for me, nothing has changed. Apart from the Question page, I'm not able to import audio files as I keep getting that prompt I attached. On empty pages it just closes. Btw, I use tmpm.exe. (Amúgy király vagy, hogy ilyen gyorsan reagáltál, azt hittem, már nem foglalkozik senki ezzel a moddal, én meg most tök rápörögtem, hogy tudok a suliban frankó összefoglaló órákat csinálni vele. :D)

**Comment by VoidXH** [comment]
Please download the latest version, and use incognito mode if you downloaded the software in the past 24 hours to prevent caching. (Na azt nem gondoltam volna, hogy magyar issue-t kapok :D)

**Comment by mistagee83** [comment]
Now it's working! Thx a lot! ;)
