### ISSUE TITLE
im not a codder

### ISSUE THREAD

**Issue by Dankypep** [VoidXH/Trivia-Murder-Party-Modder#17]
i read the README file and i still dont know what to do, do i need to put files into the murder party folder or just run a program

**Comment by VoidXH** [comment]
Just open the program and search for the game's folder in it. If you click download, it's just the code, you will find the working software under Releases.

**Comment by Dankypep** [comment]
> Just open the program and search for the game's folder in it. If you click download, it's just the code, you will find the working software under Releases.

whats the file type?

**Comment by VoidXH** [comment]
> whats the file type?

It's a zip you can download from [this site](https://sbence.hu/index.php?l=en&t=128). The Release links take you here too. Unzip it and launch the executable.
