### ISSUE TITLE
Program just crashes on import

### ISSUE THREAD

**Issue by Shonagon-Sei** [VoidXH/Trivia-Murder-Party-Modder#19]
I'm trying to mod TMP2 with this tool and when I import the a singular file (Not Import all) the program freezes before crashing a bit later

**Comment by VoidXH** [comment]
This is not reproducible. Do you import the correct file, games\TriviaDeath2\content\TDQuestion.jet?

**Comment by VoidXH** [comment]
Please reopen if still present.
