### ISSUE TITLE
TMPM Crashes When Importing TMP2

### ISSUE THREAD

**Issue by AubbyLobby** [VoidXH/Trivia-Murder-Party-Modder#21]
When trying to import TDQuestion.jet and TDFinalRound.jet from the TMP2 files, the program crashes after a few seconds of loading. I followed the guide provided perfectly, and I legally own JPP6 on Steam.

**Comment by VoidXH** [comment]
Please try the latest version [from here](https://en.sbence.hu/index.php?t=128)

**Comment by VoidXH** [comment]
f7ed2fa74a618ebce351162ccace7323e92ed00d confirmed opening and saving the files, game compatibility is not checked but some data is confirmed lost. Added a note to the readme that using this for TMP2 is not recommended.
